SELECT
    HOUR(TIMESTAMP) as HOUR_NUM,
    COUNT(*) as NUM_TRANSACTIONS,
    SUM(AMOUNT_ETH) as TOTAL_ETH,
    AVG(AMOUNT_ETH) as AVG_ETH,
    SUM(GAS_COST_ETH) as TOTAL_GAS_COST
FROM {{ source('snowflake', 'ETH_STAKING_TRANSACTIONS') }}
GROUP BY HOUR_NUM
ORDER BY HOUR_NUM
LIMIT 24