SELECT
    DATE_TRUNC('HOUR', TIMESTAMP) as HOUR,
    COUNT(*) as NUM_TRANSACTIONS,
    SUM(AMOUNT_ETH) as TOTAL_ETH,
    AVG(AMOUNT_ETH) as AVG_ETH,
    SUM(GAS_COST_ETH) as TOTAL_GAS_COST
FROM {{ source('snowflake', 'ETH_STAKING_TRANSACTIONS') }}
GROUP BY DATE_TRUNC('HOUR', TIMESTAMP)
ORDER BY HOUR DESC