SELECT
    TRANSACTION_HASH,
    SENDER_ADDRESS,
    AMOUNT_ETH,
    TIMESTAMP_STR as TIMESTAMP,
    GAS_COST_ETH
FROM {{ source('snowflake', 'ETH_STAKING_TRANSACTIONS') }}
ORDER BY TO_TIMESTAMP_NTZ(TIMESTAMP_STR) DESC
LIMIT 10